# Placeholder to run action on feature branches
name: Python SDK CI

on:
  push:
    paths:
      - "python_sdk/**"
    branches: [ "feature/2.0.0", "feature/2.0.0-release", "feature/2.0.0-ts", "main" ]
  pull_request:
    paths: 
      - "python_sdk/**"
    branches: [ "feature/2.0.0", "feature/2.0.0-release", "main" ]
  workflow_dispatch:
