name: Python SDK CI

on:
  push:
    paths:
      - "python_sdk/**"
    branches: [ "main" ]
  pull_request:
    paths: 
      - "python_sdk/**"
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_test_sdk:
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
      
    uses: ./.github/workflows/python-build-and-test.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
