name: Publish Typescript Reality Capture SDK Pre-release

on: workflow_dispatch

# Creates a pre-release in GitHub repo. Does not publish to npm.
# Does not create pre release for reality-data-client.
jobs:
  build_and_test_sdk:
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    uses: ./.github/workflows/typescript-build-and-test.yml
    with:
      node-version: ${{ matrix.node-version }}
      os: ${{ matrix.os }}
  
  create_pre_release:
    needs: build_and_test_sdk
    strategy:
      matrix:
        node-version: [22.x]
        os: [windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        working-directory: ./
        run: pnpm install --frozen-lockfile=true

      - name: Build
        working-directory: ./
        run: pnpm build

      - name: Publish packages as tgz
        working-directory: ./typescript/reality-capture
        run: pnpm bundle

      - name: Get version
        id: get_version
        working-directory: ./typescript/reality-capture
        shell: pwsh
        run: | 
          $packageVersion=(Get-Content .\package.json | ConvertFrom-Json).version
          Write-Output "version=$($packageVersion)" >> $Env:GITHUB_OUTPUT

      - name: Create Pre-Release
        uses: softprops/action-gh-release@v2
        id: create_pre_release
        with:
          tag_name: ${{ steps.get_version.outputs.version }}-ts
          name: "Typescript Version ${{ steps.get_version.outputs.version }}"
          draft: true
          prerelease: true
          files: | 
            ./typescript/reality-capture/lib/reality-capture-${{ steps.get_version.outputs.version }}.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
