name: Typescript SDK CI

on:
  push:
    paths:
      - "typescript/**"
    branches: [ "feature/2.0.0", "feature/2.0.0-release", "feature/2.0.0-ts", "main", "tmp/CN/2rc_MergeMain" ]
  pull_request:
    paths:
      - "typescript/**"
    branches: [ "feature/2.0.0", "feature/2.0.0-release", "feature/2.0.0-ts", "main", "tmp/CN/2rc_MergeMain" ]
  workflow_dispatch:

jobs:
  build_and_test_sdk:
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    uses: ./.github/workflows/steps/typescript-build-and-test.yml
    with:
      node-version: ${{ matrix.node-version }}
      os: ${{ matrix.os }}
