name: Typescript SDK PR Workflow

on:
  pull_request:
    paths:
      - "typescript/**"
    branches: [ "feature/2.0.0", "feature/2.0.0-release", "feature/2.0.0-ts" ]

jobs:
  build_and_test_sdk:
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        operating-system: [windows-latest, windows-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        working-directory: ./typescript/reality_capture
        run: npm install --frozen-lockfile=true

      - name: Build
        working-directory: ./typescript/reality_capture
        run: npm build

      # - name: Build doc

      # - name: Run unit tests
      #   env:
      #     IMJS_UNIT_TESTS_PROJECT_ID: ${{ secrets.UNIT_TESTS_PROJECT_ID }}
      #     IMJS_UNIT_TESTS_CLIENT_ID: ${{ secrets.UNIT_TESTS_CLIENT_ID }}
      #     IMJS_UNIT_TESTS_SECRET: ${{ secrets.UNIT_TESTS_SECRET }}
      #   run: pnpm coverage
