name: Typescript workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [windows-latest]
    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setup Azure Artifacts Authentication
        run: |
          npm config set @bentley:registry https://pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/
          npm config set @itwin:registry https://pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/
          npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/:username=VssSessionToken
          npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/:_password=${{ secrets.NPM_TOKEN }}
          npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/:email=not-used@example.com
      - name: Install SDK
        working-directory: ./typescript/sdk
        run: npm install --no-save
      - name: Typescript compiler (SDK)
        working-directory: ./typescript/sdk
        run: npx tsc
      - name: Install WebApp
        working-directory: ./typescript/web-app
        run: npm install --no-save
      - name: Install Examples
        working-directory: ./typescript/examples
        run: npm install --no-save
      - name: Typescript compiler (WebApp)
        working-directory: ./typescript/web-app
        run: npx tsc
      - name: Typescript compiler (Examples)
        working-directory: ./typescript/sdk
        run: npx tsc
      - name: EsLint
        working-directory: ./typescript/web-app
        run: npm run lint
      - name: SDK integration tests
        working-directory: ./typescript/integration-tests
        env:
          IMJS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          IMJS_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          IMJS_SECRET: ${{ secrets.SECRET }}
        run: npm run test:integration
